### ISSUE TITLE
After upgrading to Angular 6 cant build with AOT

### ISSUE THREAD

**Issue by ovesyan19** [akveo/ng2-smart-table#808] opened 2018-06-11 05:25 UTC
ERROR in : Unexpected value 'Ng2SmartTableModule in /node_modules/ng2-smart-table/ng2-smart-table.module.d.ts' imported by the module 'AppModule in app.module.ts'. Please add a @NgModule annotation.

**Comment by vsiddharthv** [comment] 2018-06-11 11:33
Same issue here : 

ERROR in : Unexpected value 'Ng2SmartTableModule in ~/node_modules/ng2-smart-table/ng2-smart-table.module.d.ts' imported by the module 'AppModule in ~/src/app/app.module.ts'. Please add a @NgModule annotation.

**Comment by Syperia** [comment] 2018-06-11 11:56
This pull request fixes this issue: https://github.com/akveo/ng2-smart-table/pull/801. Currently merged. We're all waiting for release.

**Comment by nnixaa** [comment] 2018-06-12 09:40
Duplicate of #798

**Closed by nnixaa** 2018-06-12 09:40 UTC
