### ISSUE TITLE
Catching event from custom render component

### ISSUE THREAD

**Issue by dukle** [akveo/ng2-smart-table#444] opened 2017-07-16 22:38 UTC
I'm trying to catch emitted event from custom component that is being rendered by the table. Is that possible?

**Comment by loreley-larisa** [comment] 2017-08-02 17:05
Hi, I have the same issue. If you already figure it out how to catch the emitted event, please let me know.
Thanks

**Comment by RenaudF** [comment] 2017-09-20 09:59
looks like a duplicate of https://github.com/akveo/ng2-smart-table/issues/423

**Closed** 2018-03-28 13:36 UTC
